<?php include('_includes/header.php'); ?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Your Profile</h1>
  <!--
  <div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group mr-2">
  <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
  <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
</div>
<button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
<span data-feather="calendar"></span>
This week
</button>
</div>
-->
</div>

<div class="row">
  <div class="col-md-4 order-md-2 mb-4">
    <?php $phones = json_decode($user['phone']); ?>
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Your phone numbers</span>
      <span class="badge badge-secondary badge-pill"><?php echo count($phones); ?></span>
    </h4>

    <ul class="list-group mb-3">
      <?php foreach ($phones as $phone) { ?>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0"><?php echo $phone; ?></h6>
        </div>
        <button type="button" data-phone="<?php echo $phone; ?>" class="btn btn-sm btn-phone-delete btn-outline-danger">Delete</button>
      </li>
    <?php } ?>
    </ul>

    <form class="card p-2" method="post" action="updatePhone">
      <div class="input-group">
        <input type="text" class="form-control" name="inputPhone" placeholder="Phone Number" required>
        <div class="input-group-append">
          <button type="submit" class="btn btn-secondary">Add</button>
        </div>
      </div>
    </form>
  </div>

  <div class="col-md-8">
    <form class="needs-validation" action="update" method="post">

      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="username">Username</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">@</span>
            </div>
            <input type="text" class="form-control" id="username" placeholder="Username" value="<?php echo $user['username']; ?>" disabled>
            <div class="invalid-feedback" style="width: 100%;">
              Your username is required.
            </div>
          </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="inputEmail">Email</label>
          <input type="email" class="form-control" id="inputEmail" name="inputEmail" placeholder="you@example.com" value="<?php echo $user['email']; ?>" required>
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="inputFName">First name</label>
          <input type="text" class="form-control" id="inputFName" name="inputFName" placeholder="" value="<?php echo $user['f_name']; ?>">
          <div class="invalid-feedback">
            Valid first name is required.
          </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="inputLName">Last name</label>
          <input type="text" class="form-control" id="inputLName" name="inputLName" placeholder="" value="<?php echo $user['l_name']; ?>">
          <div class="invalid-feedback">
            Valid last name is required.
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 mb-3">
          <label for="inputBDate">Date Of Birth</label>
          <input type="date" class="form-control" id="inputBDate" name="inputBDate" placeholder="10/12/1990" value="<?php echo $user['b_date']; ?>">
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="inputGender">Gender</label>
          <select class="custom-select d-block w-100" id="inputGender" name="inputGender">
            <option value="">Choose...</option>
            <option <?php echo ($user['gender'] == 'Male'?'selected':''); ?>>Male</option>
            <option <?php echo ($user['gender'] == 'Female'?'selected':''); ?>>Female</option>
          </select>
          <div class="invalid-feedback">
            Please provide a valid state.
          </div>
        </div>
      </div>

      <hr class="mb-4">
      <div class="row">
        <div class="col-md-4 mb-3">
          <label for="inputCountry">Country</label>
          <select class="custom-select d-block w-100" id="inputCountry" name="inputCountry">
            <option value="">Choose...</option>
            <?php
            foreach ($countries as $country) {
              echo "<option value='" .$country['id']. "' " . ($user['country'] == $country['id']?'selected':'') . ">".$country['name']."</option>";
            } ?>
          </select>
          <div class="invalid-feedback">
            Please select a valid country.
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="inputState">State</label>
          <select class="custom-select d-block w-100" id="inputState" name="inputState">
            <option value="">Choose...</option>
            <?php
            foreach ($states as $state) {
              echo "<option value='" .$state['id']. "' " . ($user['state'] == $state['id']?'selected':'') . ">".$state['name']."</option>";
            } ?>
          </select>
          <div class="invalid-feedback">
            Please provide a valid state.
          </div>
        </div>
        <div class="col-md-4 mb-3">
          <label for="inputCity">City</label>
          <select class="custom-select d-block w-100" id="inputCity" name="inputCity">
            <option value="">Choose...</option>
            <?php
            foreach ($cities as $city) {
              echo "<option value='" .$city['id']. "' " . ($user['city'] == $city['id']?'selected':'') . ">".$city['name']."</option>";
            } ?>
          </select>
          <div class="invalid-feedback">
            Zip code required.????
          </div>
        </div>
      </div>

      <div class="mb-3">
        <label for="inputInterests">Interests</label>
        <textarea class="form-control" id="inputInterests" name="inputInterests" rows="8" cols="80" ><?php echo $user['interests']; ?></textarea>
        <div class="invalid-feedback">
          Please enter your shipping address.
        </div>
      </div>

      <hr class="mb-4">
      <button class="btn btn-primary btn-lg btn-block" type="submit">Save changes</button>
    </form>
  </div>
</div>


<?php include('_includes/footer.php'); ?>
