<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>Signin Template · Bootstrap</title>

  <link href="/assets/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <link href="/assets/css/common.css" rel="stylesheet">
</head>
<body class="text-center">
  <div class="container">


      <?php
      if($errors){
        echo '<div class="row"><div class="alert alert-warning" style="margin:0 auto;">';
      foreach ($errors as $paramErrors) {
        foreach ($paramErrors as $error) {
          echo "<p>".$error."</p>";
        }
      }
      echo "</div></div>";
    }?>


  <div class="hereForm row">

  </div>
</div>

  <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
  <script type="text/babel" src="/assets/js/homeApp.js"></script>
</body>
</html>
